// Code generated by `go run generate_ids.go`. DO NOT EDIT..

// Copyright 2017 Tom Thorogood. All rights reserved.
// Use of this source code is governed by a Modified
// BSD License that can be found in the LICENSE file.

package id3v2

const (
	FrameAENC FrameID = 'A'<<24 | 'E'<<16 | 'N'<<8 | 'C' // Audio encryption
	FrameAPIC FrameID = 'A'<<24 | 'P'<<16 | 'I'<<8 | 'C' // Attached picture
	FrameASPI FrameID = 'A'<<24 | 'S'<<16 | 'P'<<8 | 'I' // Audio seek point index
	FrameCOMM FrameID = 'C'<<24 | 'O'<<16 | 'M'<<8 | 'M' // Comments
	FrameCOMR FrameID = 'C'<<24 | 'O'<<16 | 'M'<<8 | 'R' // Commercial frame
	FrameENCR FrameID = 'E'<<24 | 'N'<<16 | 'C'<<8 | 'R' // Encryption method registration
	FrameEQU2 FrameID = 'E'<<24 | 'Q'<<16 | 'U'<<8 | '2' // Equalisation (2)
	FrameETCO FrameID = 'E'<<24 | 'T'<<16 | 'C'<<8 | 'O' // Event timing codes
	FrameGEOB FrameID = 'G'<<24 | 'E'<<16 | 'O'<<8 | 'B' // General encapsulated object
	FrameGRID FrameID = 'G'<<24 | 'R'<<16 | 'I'<<8 | 'D' // Group identification registration
	FrameLINK FrameID = 'L'<<24 | 'I'<<16 | 'N'<<8 | 'K' // Linked information
	FrameMCDI FrameID = 'M'<<24 | 'C'<<16 | 'D'<<8 | 'I' // Music CD identifier
	FrameMLLT FrameID = 'M'<<24 | 'L'<<16 | 'L'<<8 | 'T' // MPEG location lookup table
	FrameOWNE FrameID = 'O'<<24 | 'W'<<16 | 'N'<<8 | 'E' // Ownership frame
	FramePRIV FrameID = 'P'<<24 | 'R'<<16 | 'I'<<8 | 'V' // Private frame
	FramePCNT FrameID = 'P'<<24 | 'C'<<16 | 'N'<<8 | 'T' // Play counter
	FramePOPM FrameID = 'P'<<24 | 'O'<<16 | 'P'<<8 | 'M' // Popularimeter
	FramePOSS FrameID = 'P'<<24 | 'O'<<16 | 'S'<<8 | 'S' // Position synchronisation frame
	FrameRBUF FrameID = 'R'<<24 | 'B'<<16 | 'U'<<8 | 'F' // Recommended buffer size
	FrameRVA2 FrameID = 'R'<<24 | 'V'<<16 | 'A'<<8 | '2' // Relative volume adjustment (2)
	FrameRVRB FrameID = 'R'<<24 | 'V'<<16 | 'R'<<8 | 'B' // Reverb
	FrameSEEK FrameID = 'S'<<24 | 'E'<<16 | 'E'<<8 | 'K' // Seek frame
	FrameSIGN FrameID = 'S'<<24 | 'I'<<16 | 'G'<<8 | 'N' // Signature frame
	FrameSYLT FrameID = 'S'<<24 | 'Y'<<16 | 'L'<<8 | 'T' // Synchronised lyric/text
	FrameSYTC FrameID = 'S'<<24 | 'Y'<<16 | 'T'<<8 | 'C' // Synchronised tempo codes
	FrameTALB FrameID = 'T'<<24 | 'A'<<16 | 'L'<<8 | 'B' // Album/Movie/Show title
	FrameTBPM FrameID = 'T'<<24 | 'B'<<16 | 'P'<<8 | 'M' // BPM (beats per minute)
	FrameTCOM FrameID = 'T'<<24 | 'C'<<16 | 'O'<<8 | 'M' // Composer
	FrameTCON FrameID = 'T'<<24 | 'C'<<16 | 'O'<<8 | 'N' // Content type
	FrameTCOP FrameID = 'T'<<24 | 'C'<<16 | 'O'<<8 | 'P' // Copyright message
	FrameTDEN FrameID = 'T'<<24 | 'D'<<16 | 'E'<<8 | 'N' // Encoding time
	FrameTDLY FrameID = 'T'<<24 | 'D'<<16 | 'L'<<8 | 'Y' // Playlist delay
	FrameTDOR FrameID = 'T'<<24 | 'D'<<16 | 'O'<<8 | 'R' // Original release time
	FrameTDRC FrameID = 'T'<<24 | 'D'<<16 | 'R'<<8 | 'C' // Recording time
	FrameTDRL FrameID = 'T'<<24 | 'D'<<16 | 'R'<<8 | 'L' // Release time
	FrameTDTG FrameID = 'T'<<24 | 'D'<<16 | 'T'<<8 | 'G' // Tagging time
	FrameTENC FrameID = 'T'<<24 | 'E'<<16 | 'N'<<8 | 'C' // Encoded by
	FrameTEXT FrameID = 'T'<<24 | 'E'<<16 | 'X'<<8 | 'T' // Lyricist/Text writer
	FrameTFLT FrameID = 'T'<<24 | 'F'<<16 | 'L'<<8 | 'T' // File type
	FrameTIPL FrameID = 'T'<<24 | 'I'<<16 | 'P'<<8 | 'L' // Involved people list
	FrameTIT1 FrameID = 'T'<<24 | 'I'<<16 | 'T'<<8 | '1' // Content group description
	FrameTIT2 FrameID = 'T'<<24 | 'I'<<16 | 'T'<<8 | '2' // Title/songname/content description
	FrameTIT3 FrameID = 'T'<<24 | 'I'<<16 | 'T'<<8 | '3' // Subtitle/Description refinement
	FrameTKEY FrameID = 'T'<<24 | 'K'<<16 | 'E'<<8 | 'Y' // Initial key
	FrameTLAN FrameID = 'T'<<24 | 'L'<<16 | 'A'<<8 | 'N' // Language(s)
	FrameTLEN FrameID = 'T'<<24 | 'L'<<16 | 'E'<<8 | 'N' // Length
	FrameTMCL FrameID = 'T'<<24 | 'M'<<16 | 'C'<<8 | 'L' // Musician credits list
	FrameTMED FrameID = 'T'<<24 | 'M'<<16 | 'E'<<8 | 'D' // Media type
	FrameTMOO FrameID = 'T'<<24 | 'M'<<16 | 'O'<<8 | 'O' // Mood
	FrameTOAL FrameID = 'T'<<24 | 'O'<<16 | 'A'<<8 | 'L' // Original album/movie/show title
	FrameTOFN FrameID = 'T'<<24 | 'O'<<16 | 'F'<<8 | 'N' // Original filename
	FrameTOLY FrameID = 'T'<<24 | 'O'<<16 | 'L'<<8 | 'Y' // Original lyricist(s)/text writer(s)
	FrameTOPE FrameID = 'T'<<24 | 'O'<<16 | 'P'<<8 | 'E' // Original artist(s)/performer(s)
	FrameTOWN FrameID = 'T'<<24 | 'O'<<16 | 'W'<<8 | 'N' // File owner/licensee
	FrameTPE1 FrameID = 'T'<<24 | 'P'<<16 | 'E'<<8 | '1' // Lead performer(s)/Soloist(s)
	FrameTPE2 FrameID = 'T'<<24 | 'P'<<16 | 'E'<<8 | '2' // Band/orchestra/accompaniment
	FrameTPE3 FrameID = 'T'<<24 | 'P'<<16 | 'E'<<8 | '3' // Conductor/performer refinement
	FrameTPE4 FrameID = 'T'<<24 | 'P'<<16 | 'E'<<8 | '4' // Interpreted, remixed, or otherwise modified by
	FrameTPOS FrameID = 'T'<<24 | 'P'<<16 | 'O'<<8 | 'S' // Part of a set
	FrameTPRO FrameID = 'T'<<24 | 'P'<<16 | 'R'<<8 | 'O' // Produced notice
	FrameTPUB FrameID = 'T'<<24 | 'P'<<16 | 'U'<<8 | 'B' // Publisher
	FrameTRCK FrameID = 'T'<<24 | 'R'<<16 | 'C'<<8 | 'K' // Track number/Position in set
	FrameTRSN FrameID = 'T'<<24 | 'R'<<16 | 'S'<<8 | 'N' // Internet radio station name
	FrameTRSO FrameID = 'T'<<24 | 'R'<<16 | 'S'<<8 | 'O' // Internet radio station owner
	FrameTSOA FrameID = 'T'<<24 | 'S'<<16 | 'O'<<8 | 'A' // Album sort order
	FrameTSOP FrameID = 'T'<<24 | 'S'<<16 | 'O'<<8 | 'P' // Performer sort order
	FrameTSOT FrameID = 'T'<<24 | 'S'<<16 | 'O'<<8 | 'T' // Title sort order
	FrameTSRC FrameID = 'T'<<24 | 'S'<<16 | 'R'<<8 | 'C' // ISRC (international standard recording code)
	FrameTSSE FrameID = 'T'<<24 | 'S'<<16 | 'S'<<8 | 'E' // Software/Hardware and settings used for encoding
	FrameTSST FrameID = 'T'<<24 | 'S'<<16 | 'S'<<8 | 'T' // Set subtitle
	FrameTXXX FrameID = 'T'<<24 | 'X'<<16 | 'X'<<8 | 'X' // User defined text information frame
	FrameUFID FrameID = 'U'<<24 | 'F'<<16 | 'I'<<8 | 'D' // Unique file identifier
	FrameUSER FrameID = 'U'<<24 | 'S'<<16 | 'E'<<8 | 'R' // Terms of use
	FrameUSLT FrameID = 'U'<<24 | 'S'<<16 | 'L'<<8 | 'T' // Unsynchronised lyric/text transcription
	FrameWCOM FrameID = 'W'<<24 | 'C'<<16 | 'O'<<8 | 'M' // Commercial information
	FrameWCOP FrameID = 'W'<<24 | 'C'<<16 | 'O'<<8 | 'P' // Copyright/Legal information
	FrameWOAF FrameID = 'W'<<24 | 'O'<<16 | 'A'<<8 | 'F' // Official audio file webpage
	FrameWOAR FrameID = 'W'<<24 | 'O'<<16 | 'A'<<8 | 'R' // Official artist/performer webpage
	FrameWOAS FrameID = 'W'<<24 | 'O'<<16 | 'A'<<8 | 'S' // Official audio source webpage
	FrameWORS FrameID = 'W'<<24 | 'O'<<16 | 'R'<<8 | 'S' // Official Internet radio station homepage
	FrameWPAY FrameID = 'W'<<24 | 'P'<<16 | 'A'<<8 | 'Y' // Payment
	FrameWPUB FrameID = 'W'<<24 | 'P'<<16 | 'U'<<8 | 'B' // Publishers official webpage
	FrameWXXX FrameID = 'W'<<24 | 'X'<<16 | 'X'<<8 | 'X' // User defined URL link frame
	FrameEQUA FrameID = 'E'<<24 | 'Q'<<16 | 'U'<<8 | 'A' // Equalization
	FrameIPLS FrameID = 'I'<<24 | 'P'<<16 | 'L'<<8 | 'S' // Involved people list
	FrameRVAD FrameID = 'R'<<24 | 'V'<<16 | 'A'<<8 | 'D' // Relative volume adjustment
	FrameTDAT FrameID = 'T'<<24 | 'D'<<16 | 'A'<<8 | 'T' // Date
	FrameTIME FrameID = 'T'<<24 | 'I'<<16 | 'M'<<8 | 'E' // Time
	FrameTORY FrameID = 'T'<<24 | 'O'<<16 | 'R'<<8 | 'Y' // Original release year
	FrameTRDA FrameID = 'T'<<24 | 'R'<<16 | 'D'<<8 | 'A' // Recording dates
	FrameTSIZ FrameID = 'T'<<24 | 'S'<<16 | 'I'<<8 | 'Z' // Size
	FrameTYER FrameID = 'T'<<24 | 'Y'<<16 | 'E'<<8 | 'R' // Year
)

func (id FrameID) String() string {
	switch id {
	case 'A'<<24 | 'E'<<16 | 'N'<<8 | 'C':
		return "AENC: Audio encryption"
	case 'A'<<24 | 'P'<<16 | 'I'<<8 | 'C':
		return "APIC: Attached picture"
	case 'A'<<24 | 'S'<<16 | 'P'<<8 | 'I':
		return "ASPI: Audio seek point index"
	case 'C'<<24 | 'O'<<16 | 'M'<<8 | 'M':
		return "COMM: Comments"
	case 'C'<<24 | 'O'<<16 | 'M'<<8 | 'R':
		return "COMR: Commercial frame"
	case 'E'<<24 | 'N'<<16 | 'C'<<8 | 'R':
		return "ENCR: Encryption method registration"
	case 'E'<<24 | 'Q'<<16 | 'U'<<8 | '2':
		return "EQU2: Equalisation (2)"
	case 'E'<<24 | 'T'<<16 | 'C'<<8 | 'O':
		return "ETCO: Event timing codes"
	case 'G'<<24 | 'E'<<16 | 'O'<<8 | 'B':
		return "GEOB: General encapsulated object"
	case 'G'<<24 | 'R'<<16 | 'I'<<8 | 'D':
		return "GRID: Group identification registration"
	case 'L'<<24 | 'I'<<16 | 'N'<<8 | 'K':
		return "LINK: Linked information"
	case 'M'<<24 | 'C'<<16 | 'D'<<8 | 'I':
		return "MCDI: Music CD identifier"
	case 'M'<<24 | 'L'<<16 | 'L'<<8 | 'T':
		return "MLLT: MPEG location lookup table"
	case 'O'<<24 | 'W'<<16 | 'N'<<8 | 'E':
		return "OWNE: Ownership frame"
	case 'P'<<24 | 'R'<<16 | 'I'<<8 | 'V':
		return "PRIV: Private frame"
	case 'P'<<24 | 'C'<<16 | 'N'<<8 | 'T':
		return "PCNT: Play counter"
	case 'P'<<24 | 'O'<<16 | 'P'<<8 | 'M':
		return "POPM: Popularimeter"
	case 'P'<<24 | 'O'<<16 | 'S'<<8 | 'S':
		return "POSS: Position synchronisation frame"
	case 'R'<<24 | 'B'<<16 | 'U'<<8 | 'F':
		return "RBUF: Recommended buffer size"
	case 'R'<<24 | 'V'<<16 | 'A'<<8 | '2':
		return "RVA2: Relative volume adjustment (2)"
	case 'R'<<24 | 'V'<<16 | 'R'<<8 | 'B':
		return "RVRB: Reverb"
	case 'S'<<24 | 'E'<<16 | 'E'<<8 | 'K':
		return "SEEK: Seek frame"
	case 'S'<<24 | 'I'<<16 | 'G'<<8 | 'N':
		return "SIGN: Signature frame"
	case 'S'<<24 | 'Y'<<16 | 'L'<<8 | 'T':
		return "SYLT: Synchronised lyric/text"
	case 'S'<<24 | 'Y'<<16 | 'T'<<8 | 'C':
		return "SYTC: Synchronised tempo codes"
	case 'T'<<24 | 'A'<<16 | 'L'<<8 | 'B':
		return "TALB: Album/Movie/Show title"
	case 'T'<<24 | 'B'<<16 | 'P'<<8 | 'M':
		return "TBPM: BPM (beats per minute)"
	case 'T'<<24 | 'C'<<16 | 'O'<<8 | 'M':
		return "TCOM: Composer"
	case 'T'<<24 | 'C'<<16 | 'O'<<8 | 'N':
		return "TCON: Content type"
	case 'T'<<24 | 'C'<<16 | 'O'<<8 | 'P':
		return "TCOP: Copyright message"
	case 'T'<<24 | 'D'<<16 | 'E'<<8 | 'N':
		return "TDEN: Encoding time"
	case 'T'<<24 | 'D'<<16 | 'L'<<8 | 'Y':
		return "TDLY: Playlist delay"
	case 'T'<<24 | 'D'<<16 | 'O'<<8 | 'R':
		return "TDOR: Original release time"
	case 'T'<<24 | 'D'<<16 | 'R'<<8 | 'C':
		return "TDRC: Recording time"
	case 'T'<<24 | 'D'<<16 | 'R'<<8 | 'L':
		return "TDRL: Release time"
	case 'T'<<24 | 'D'<<16 | 'T'<<8 | 'G':
		return "TDTG: Tagging time"
	case 'T'<<24 | 'E'<<16 | 'N'<<8 | 'C':
		return "TENC: Encoded by"
	case 'T'<<24 | 'E'<<16 | 'X'<<8 | 'T':
		return "TEXT: Lyricist/Text writer"
	case 'T'<<24 | 'F'<<16 | 'L'<<8 | 'T':
		return "TFLT: File type"
	case 'T'<<24 | 'I'<<16 | 'P'<<8 | 'L':
		return "TIPL: Involved people list"
	case 'T'<<24 | 'I'<<16 | 'T'<<8 | '1':
		return "TIT1: Content group description"
	case 'T'<<24 | 'I'<<16 | 'T'<<8 | '2':
		return "TIT2: Title/songname/content description"
	case 'T'<<24 | 'I'<<16 | 'T'<<8 | '3':
		return "TIT3: Subtitle/Description refinement"
	case 'T'<<24 | 'K'<<16 | 'E'<<8 | 'Y':
		return "TKEY: Initial key"
	case 'T'<<24 | 'L'<<16 | 'A'<<8 | 'N':
		return "TLAN: Language(s)"
	case 'T'<<24 | 'L'<<16 | 'E'<<8 | 'N':
		return "TLEN: Length"
	case 'T'<<24 | 'M'<<16 | 'C'<<8 | 'L':
		return "TMCL: Musician credits list"
	case 'T'<<24 | 'M'<<16 | 'E'<<8 | 'D':
		return "TMED: Media type"
	case 'T'<<24 | 'M'<<16 | 'O'<<8 | 'O':
		return "TMOO: Mood"
	case 'T'<<24 | 'O'<<16 | 'A'<<8 | 'L':
		return "TOAL: Original album/movie/show title"
	case 'T'<<24 | 'O'<<16 | 'F'<<8 | 'N':
		return "TOFN: Original filename"
	case 'T'<<24 | 'O'<<16 | 'L'<<8 | 'Y':
		return "TOLY: Original lyricist(s)/text writer(s)"
	case 'T'<<24 | 'O'<<16 | 'P'<<8 | 'E':
		return "TOPE: Original artist(s)/performer(s)"
	case 'T'<<24 | 'O'<<16 | 'W'<<8 | 'N':
		return "TOWN: File owner/licensee"
	case 'T'<<24 | 'P'<<16 | 'E'<<8 | '1':
		return "TPE1: Lead performer(s)/Soloist(s)"
	case 'T'<<24 | 'P'<<16 | 'E'<<8 | '2':
		return "TPE2: Band/orchestra/accompaniment"
	case 'T'<<24 | 'P'<<16 | 'E'<<8 | '3':
		return "TPE3: Conductor/performer refinement"
	case 'T'<<24 | 'P'<<16 | 'E'<<8 | '4':
		return "TPE4: Interpreted, remixed, or otherwise modified by"
	case 'T'<<24 | 'P'<<16 | 'O'<<8 | 'S':
		return "TPOS: Part of a set"
	case 'T'<<24 | 'P'<<16 | 'R'<<8 | 'O':
		return "TPRO: Produced notice"
	case 'T'<<24 | 'P'<<16 | 'U'<<8 | 'B':
		return "TPUB: Publisher"
	case 'T'<<24 | 'R'<<16 | 'C'<<8 | 'K':
		return "TRCK: Track number/Position in set"
	case 'T'<<24 | 'R'<<16 | 'S'<<8 | 'N':
		return "TRSN: Internet radio station name"
	case 'T'<<24 | 'R'<<16 | 'S'<<8 | 'O':
		return "TRSO: Internet radio station owner"
	case 'T'<<24 | 'S'<<16 | 'O'<<8 | 'A':
		return "TSOA: Album sort order"
	case 'T'<<24 | 'S'<<16 | 'O'<<8 | 'P':
		return "TSOP: Performer sort order"
	case 'T'<<24 | 'S'<<16 | 'O'<<8 | 'T':
		return "TSOT: Title sort order"
	case 'T'<<24 | 'S'<<16 | 'R'<<8 | 'C':
		return "TSRC: ISRC (international standard recording code)"
	case 'T'<<24 | 'S'<<16 | 'S'<<8 | 'E':
		return "TSSE: Software/Hardware and settings used for encoding"
	case 'T'<<24 | 'S'<<16 | 'S'<<8 | 'T':
		return "TSST: Set subtitle"
	case 'T'<<24 | 'X'<<16 | 'X'<<8 | 'X':
		return "TXXX: User defined text information frame"
	case 'U'<<24 | 'F'<<16 | 'I'<<8 | 'D':
		return "UFID: Unique file identifier"
	case 'U'<<24 | 'S'<<16 | 'E'<<8 | 'R':
		return "USER: Terms of use"
	case 'U'<<24 | 'S'<<16 | 'L'<<8 | 'T':
		return "USLT: Unsynchronised lyric/text transcription"
	case 'W'<<24 | 'C'<<16 | 'O'<<8 | 'M':
		return "WCOM: Commercial information"
	case 'W'<<24 | 'C'<<16 | 'O'<<8 | 'P':
		return "WCOP: Copyright/Legal information"
	case 'W'<<24 | 'O'<<16 | 'A'<<8 | 'F':
		return "WOAF: Official audio file webpage"
	case 'W'<<24 | 'O'<<16 | 'A'<<8 | 'R':
		return "WOAR: Official artist/performer webpage"
	case 'W'<<24 | 'O'<<16 | 'A'<<8 | 'S':
		return "WOAS: Official audio source webpage"
	case 'W'<<24 | 'O'<<16 | 'R'<<8 | 'S':
		return "WORS: Official Internet radio station homepage"
	case 'W'<<24 | 'P'<<16 | 'A'<<8 | 'Y':
		return "WPAY: Payment"
	case 'W'<<24 | 'P'<<16 | 'U'<<8 | 'B':
		return "WPUB: Publishers official webpage"
	case 'W'<<24 | 'X'<<16 | 'X'<<8 | 'X':
		return "WXXX: User defined URL link frame"
	case 'E'<<24 | 'Q'<<16 | 'U'<<8 | 'A':
		return "EQUA: Equalization"
	case 'I'<<24 | 'P'<<16 | 'L'<<8 | 'S':
		return "IPLS: Involved people list"
	case 'R'<<24 | 'V'<<16 | 'A'<<8 | 'D':
		return "RVAD: Relative volume adjustment"
	case 'T'<<24 | 'D'<<16 | 'A'<<8 | 'T':
		return "TDAT: Date"
	case 'T'<<24 | 'I'<<16 | 'M'<<8 | 'E':
		return "TIME: Time"
	case 'T'<<24 | 'O'<<16 | 'R'<<8 | 'Y':
		return "TORY: Original release year"
	case 'T'<<24 | 'R'<<16 | 'D'<<8 | 'A':
		return "TRDA: Recording dates"
	case 'T'<<24 | 'S'<<16 | 'I'<<8 | 'Z':
		return "TSIZ: Size"
	case 'T'<<24 | 'Y'<<16 | 'E'<<8 | 'R':
		return "TYER: Year"
	default:
		buf := [4]byte{
			byte(id >> 24),
			byte(id >> 16),
			byte(id >> 8),
			byte(id),
		}
		return "FrameID(\"" + string(buf[:]) + "\")"
	}
}
